title_html: "<b>X</b>ingzhi <b>Zhou</b>"
description: Master student at Tokyo Institute of Technology
email: Xingzhi06Zhou@gmail.com
github_username: XingzhiZhou
baseurl: academic

theme: academic

